// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/run-readonly-query.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^3.25.76";
var FORBIDDEN = [
  "insert",
  "update",
  "delete",
  "merge",
  "alter",
  "drop",
  "create",
  "grant",
  "revoke",
  "truncate",
  "copy",
  "vacuum",
  "reindex",
  "cluster",
  "call",
  "do",
  "listen",
  "notify",
  "lock",
  "comment",
  "security",
  "set",
  "reset"
];
function stripLiteralsAndComments(sql) {
  let out = "";
  let i = 0;
  while (i < sql.length) {
    const c = sql[i];
    const next = sql[i + 1];
    if (c === "-" && next === "-") {
      const nl = sql.indexOf("\n", i);
      i = nl === -1 ? sql.length : nl;
      continue;
    }
    if (c === "/" && next === "*") {
      const end = sql.indexOf("*/", i + 2);
      i = end === -1 ? sql.length : end + 2;
      continue;
    }
    if (c === "'") {
      i++;
      while (i < sql.length) {
        if (sql[i] === "'" && sql[i + 1] === "'") {
          i += 2;
          continue;
        }
        if (sql[i] === "'") {
          i++;
          break;
        }
        i++;
      }
      out += " '' ";
      continue;
    }
    out += c;
    i++;
  }
  return out;
}
function validateReadOnly(sql) {
  const trimmed = sql.trim().replace(/;+\s*$/, "");
  if (!trimmed) return "Empty query";
  const stripped = stripLiteralsAndComments(trimmed);
  if (stripped.includes(";")) return "Multiple statements are not allowed";
  const lower = " " + stripped.toLowerCase().replace(/\s+/g, " ") + " ";
  const startsOk = /^\s*(select|with|explain\s+select|explain\s+with|table|values)\b/i.test(trimmed);
  if (!startsOk) return "Query must start with SELECT, WITH, TABLE, VALUES, or EXPLAIN SELECT/WITH";
  for (const kw of FORBIDDEN) {
    const re = new RegExp(`(^|[^a-z0-9_])${kw}([^a-z0-9_]|$)`, "i");
    if (re.test(stripped)) return `Forbidden keyword: ${kw.toUpperCase()}`;
  }
  if (/\b(pg_read_server_files|pg_write_server_files|dblink|lo_import|lo_export|pg_terminate_backend|pg_cancel_backend|pg_reload_conf)\b/i.test(stripped)) {
    return "Forbidden server-side function";
  }
  return null;
}
function supabaseForUser(ctx) {
  const url = Deno.env.get("SUPABASE_URL");
  const anon = Deno.env.get("SUPABASE_ANON_KEY") ?? Deno.env.get("SUPABASE_PUBLISHABLE_KEY");
  return createClient(url, anon, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var MAX_ROWS = 5e3;
var run_readonly_query_default = defineTool({
  name: "run_readonly_query",
  title: "Run read-only SQL query",
  description: "Execute a single read-only SQL statement (SELECT / WITH / EXPLAIN SELECT) against the app database as the signed-in user. RLS applies \u2014 you see only what the user is allowed to see. Rejects any DDL/DML (INSERT/UPDATE/DELETE/ALTER/DROP/CREATE/GRANT/TRUNCATE/COPY/SET/...), multiple statements, and unsafe server functions. Wrapped in a READ ONLY transaction with a 15s statement timeout and hard cap of 5000 rows.",
  inputSchema: {
    sql: z.string().min(1).describe("A single SELECT/WITH/EXPLAIN SELECT statement. No trailing semicolons required; multi-statement input is rejected.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sql }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const violation = validateReadOnly(sql);
    if (violation) {
      return { content: [{ type: "text", text: `Rejected: ${violation}` }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.rpc("mcp_run_readonly_query", {
      p_sql: sql,
      p_max_rows: MAX_ROWS,
      p_timeout_ms: 15e3
    });
    if (error) {
      return {
        content: [{ type: "text", text: `Query error: ${error.message}` }],
        isError: true
      };
    }
    const rows = Array.isArray(data) ? data : data ? [data] : [];
    const truncated = rows.length >= MAX_ROWS;
    const payload = { row_count: rows.length, truncated, rows };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zrgfrdmywxlemcuiqtqg";
var mcp_default = defineMcp({
  name: "fabrik-mcp",
  title: "Fabrik Performance (read-only)",
  version: "0.1.0",
  instructions: "Read-only SQL access to the Fabrik Performance database as the signed-in user. Use `run_readonly_query` to run a single SELECT/WITH/EXPLAIN SELECT statement. RLS is enforced \u2014 results are scoped to what the connected user can see. DDL/DML, multi-statement input, SET, COPY, and unsafe server functions are rejected. Transactions are READ ONLY with a 15s statement timeout and a hard cap of 5000 rows.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [run_readonly_query_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
