begin;

revoke execute on function public.get_oura_access_token(uuid)                       from public, anon, authenticated;
grant  execute on function public.get_oura_access_token(uuid)                       to service_role;
revoke execute on function public.get_oura_refresh_token(uuid)                      from public, anon, authenticated;
grant  execute on function public.get_oura_refresh_token(uuid)                      to service_role;
revoke execute on function public.store_oura_tokens(uuid, text, text, timestamp with time zone) from public, anon, authenticated;
grant  execute on function public.store_oura_tokens(uuid, text, text, timestamp with time zone) to service_role;
revoke execute on function public.cleanup_rate_limit_attempts()                     from public, anon, authenticated;
grant  execute on function public.cleanup_rate_limit_attempts()                     to service_role;
revoke execute on function public.migrate_oura_tokens_to_vault()                    from public, anon, authenticated;
grant  execute on function public.migrate_oura_tokens_to_vault()                    to service_role;
revoke execute on function public.compute_week_adherence()                          from public, anon, authenticated;
grant  execute on function public.compute_week_adherence()                          to service_role;
revoke execute on function public.update_folder_full_path()                         from public, anon, authenticated;
grant  execute on function public.update_folder_full_path()                         to service_role;

revoke execute on function public.count_active_students(date)                       from public, anon;
grant  execute on function public.count_active_students(date)                       to authenticated;
revoke execute on function public.count_students_inactive(integer)                  from public, anon;
grant  execute on function public.count_students_inactive(integer)                  to authenticated;
revoke execute on function public.count_students_frequency_dropping()               from public, anon;
grant  execute on function public.count_students_frequency_dropping()               to authenticated;
revoke execute on function public.count_prescriptions_stagnant(integer)             from public, anon;
grant  execute on function public.count_prescriptions_stagnant(integer)             to authenticated;
revoke execute on function public.list_students_inactive(integer)                   from public, anon;
grant  execute on function public.list_students_inactive(integer)                   to authenticated;
revoke execute on function public.list_students_frequency_dropping()                from public, anon;
grant  execute on function public.list_students_frequency_dropping()                to authenticated;
revoke execute on function public.list_prescriptions_stagnant(integer)              from public, anon;
grant  execute on function public.list_prescriptions_stagnant(integer)              to authenticated;
revoke execute on function public.calc_oura_baseline(uuid, integer)                 from public, anon;
grant  execute on function public.calc_oura_baseline(uuid, integer)                 to authenticated;
revoke execute on function public.delete_prescription_cascade(uuid)                 from public, anon;
grant  execute on function public.delete_prescription_cascade(uuid)                 to authenticated;
revoke execute on function public.update_prescription_with_exercises(uuid, text, text, jsonb) from public, anon;
grant  execute on function public.update_prescription_with_exercises(uuid, text, text, jsonb) to authenticated;
revoke execute on function public.create_workout_session_with_exercises(uuid, date, time without time zone, text, jsonb) from public, anon;
grant  execute on function public.create_workout_session_with_exercises(uuid, date, time without time zone, text, jsonb) to authenticated;
revoke execute on function public.create_group_workout_session_with_exercises(uuid, uuid, date, time without time zone, jsonb) from public, anon;
grant  execute on function public.create_group_workout_session_with_exercises(uuid, uuid, date, time without time zone, jsonb) to authenticated;
revoke execute on function public.list_unlinked_session_exercise_review()           from public, anon;
grant  execute on function public.list_unlinked_session_exercise_review()           to authenticated;
revoke execute on function public.search_exercises_by_name(text, text, integer)     from public, anon;
grant  execute on function public.search_exercises_by_name(text, text, integer)     to authenticated;
revoke execute on function public.normalize_objective(text)                         from public, anon;
grant  execute on function public.normalize_objective(text)                         to authenticated;

commit;