-- Dashboard KPI RPCs
--
-- ⚠ DUPLICATE / IDEMPOTENT
-- This migration was auto-generated by the deploy tool and re-applies the
-- exact same definitions already shipped in 20260502230000_add_dashboard_kpi_rpcs.sql.
-- It has already been applied in production (see commit 7d0b62c). Because every
-- statement uses CREATE OR REPLACE FUNCTION, re-running it is a no-op — the
-- function bodies are byte-identical to the canonical migration.
--
-- We KEEP this file (rather than deleting it) so the supabase migrations
-- table stays consistent with what was applied. New canonical KPI logic lives
-- in 20260502230000_add_dashboard_kpi_rpcs.sql; this file should not be
-- edited going forward.
CREATE OR REPLACE FUNCTION public.count_students_inactive(p_days integer)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  SELECT COUNT(*)::integer
  FROM students s
  WHERE s.created_at::date <= CURRENT_DATE - p_days
    AND NOT EXISTS (
      SELECT 1
      FROM workout_sessions ws
      WHERE ws.student_id = s.id
        AND ws.date >= CURRENT_DATE - p_days
    );
$$;

CREATE OR REPLACE FUNCTION public.count_students_frequency_dropping()
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH prior AS (
    SELECT student_id, COUNT(*)::integer AS prior_count
    FROM workout_sessions
    WHERE date >= CURRENT_DATE - 56
      AND date <  CURRENT_DATE - 28
    GROUP BY student_id
  ),
  recent AS (
    SELECT student_id, COUNT(*)::integer AS recent_count
    FROM workout_sessions
    WHERE date >= CURRENT_DATE - 28
      AND date <  CURRENT_DATE
    GROUP BY student_id
  )
  SELECT COUNT(*)::integer
  FROM prior p
  LEFT JOIN recent r ON r.student_id = p.student_id
  WHERE COALESCE(r.recent_count, 0) < p.prior_count
    AND p.prior_count > 0;
$$;

CREATE OR REPLACE FUNCTION public.compute_week_adherence()
 RETURNS json
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  WITH week_start AS (
    SELECT date_trunc('week', CURRENT_DATE)::date AS d
  ),
  realized_q AS (
    SELECT COUNT(*)::integer AS realized
    FROM workout_sessions, week_start
    WHERE date >= week_start.d
  ),
  prescribed_q AS (
    SELECT COALESCE(SUM(s.weekly_sessions_proposed), 0)::integer AS prescribed
    FROM students s
    WHERE EXISTS (
      SELECT 1
      FROM prescription_assignments pa
      WHERE pa.student_id = s.id
        AND pa.start_date <= CURRENT_DATE
        AND (pa.end_date IS NULL OR pa.end_date >= CURRENT_DATE)
    )
  )
  SELECT json_build_object(
    'realized', realized_q.realized,
    'prescribed', prescribed_q.prescribed,
    'percentage', CASE
      WHEN prescribed_q.prescribed > 0
        THEN ROUND((realized_q.realized::numeric / prescribed_q.prescribed) * 100, 1)
      ELSE 0
    END
  )
  FROM realized_q, prescribed_q;
$$;

CREATE OR REPLACE FUNCTION public.count_prescriptions_stagnant(p_weeks integer)
 RETURNS integer
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $$
  SELECT COUNT(DISTINCT wp.id)::integer
  FROM workout_prescriptions wp
  WHERE wp.updated_at < (CURRENT_DATE - (p_weeks * 7))::timestamp
    AND EXISTS (
      SELECT 1
      FROM prescription_assignments pa
      WHERE pa.prescription_id = wp.id
        AND pa.start_date <= CURRENT_DATE
        AND (pa.end_date IS NULL OR pa.end_date >= CURRENT_DATE)
    );
$$;